language: python

matrix:
  include:
    - python: 3.8
    - python: 3.9
      dist: xenial
      sudo: true

install:
  - pip install virtualenv tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
